import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import net from 'node:net';
import {pathToFileURL} from 'node:url';
const root=path.resolve(import.meta.dirname,'..');
test('Server: quote integrity, idempotency, comparison, budget, errors, CSRF and restart',{timeout:30000},async t=>{
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'arnie-model-lab-test-'));
 for(const f of ['server.mjs','src','public'])fs.cpSync(path.join(root,f),path.join(tmp,f),{recursive:true});
 const sock=net.createServer();sock.listen(0,'127.0.0.1');await once(sock,'listening');const port=sock.address().port;await new Promise(r=>sock.close(r));
 const env={...process.env,PORT:String(port),HF_CREDENTIALS:'test:test',MAX_SPEND_USD:'1'};
 const start=()=>spawn(process.execPath,['--import',pathToFileURL(path.join(root,'test/mock-provider.mjs')).href,'server.mjs'],{cwd:tmp,env,stdio:['ignore','pipe','pipe']});
 let child=start();t.after(()=>child.kill());
 await Promise.race([once(child.stdout,'data'),once(child.stderr,'data').then(([b])=>{throw new Error(b.toString())})]);const base=`http://127.0.0.1:${port}`;
 const bootstrap=()=>fetch(base+'/api/bootstrap').then(r=>r.json());let boot=await bootstrap();
 const post=async(p,data,token=boot.token)=>{const r=await fetch(base+p,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':token},body:JSON.stringify(data)});return {status:r.status,data:await r.json()};};
 const settings={kind:'video',prompt:'same prompt',resolution:'720p',aspectRatio:'16:9',duration:5,audio:'off'};
 const payload={mode:'comparison',modelIds:['wanprime','pixverse6'],settings,referenceIds:[]};
 assert.equal((await post('/api/start',{},'bad')).status,403);
 assert.equal((await fetch(base+'/.env')).status,404);
 assert.equal((await post('/api/budget',{limitUsd:2},'bad')).status,403);
 assert.equal((await post('/api/budget',{limitUsd:1})).data.limitUsd,1);
 assert.equal((await post('/api/estimate',{...payload,modelIds:['soul2']})).status,400);
 const six={mode:'comparison',modelIds:['grokimage2','recraft41','qwen3','zimage','soul2','ideogram4'],settings:{...settings,kind:'image',resolution:'1k',aspectRatio:'1:1'},resolutionOverrides:{soul2:'720p',ideogram4:'model'}};
 const allSix=await post('/api/estimate',six);assert.equal(allSix.status,200);assert.equal(allSix.data.entries.length,6);assert.ok(allSix.data.entries.every(e=>!e.errors.length));assert.equal(allSix.data.canStart,false);
 assert.equal(allSix.data.entries.find(e=>e.modelId==='soul2').input.resolution,'720p');assert.ok(!('resolution' in allSix.data.entries.find(e=>e.modelId==='ideogram4').input));
 assert.equal((await post('/api/estimate',{...six,resolutionOverrides:{soul2:'4k'}})).data.canStart,false);
 assert.equal((await post('/api/estimate',{...six,resolutionOverrides:{unknown:'720p'}})).status,400);
 const tariff=(await post('/api/estimate',{mode:'single',modelIds:['seedance25'],settings:{...settings,prompt:'seedance tariff',duration:6}})).data;
 assert.equal(tariff.entries[0].basis,'tariff');assert.equal(tariff.entries[0].accountUsd,null);assert.equal(tariff.entries[0].usd,2.77344);assert.equal(tariff.canStart,false);assert.equal((await post('/api/start',{quoteId:tariff.id})).status,400);
 await post('/api/budget',{limitUsd:3});assert.equal((await post('/api/estimate',{mode:'single',modelIds:['seedance25'],settings:{...settings,prompt:'seedance tariff',duration:6}})).data.canStart,true);await post('/api/budget',{limitUsd:1});
 let q=(await post('/api/estimate',payload)).data;assert.equal(q.totalUsd,.4);assert.equal(q.canStart,true);
 const result=await Promise.all([post('/api/start',{quoteId:q.id}),post('/api/start',{quoteId:q.id})]);assert.equal(result[0].data.runId,result[1].data.runId);
 await new Promise(r=>setTimeout(r,2200));let data=await fetch(base+'/api/runs').then(r=>r.json());assert.equal(data.runs.length,1);assert.equal(data.runs[0].jobs.length,2);assert.equal(data.runs[0].actualUsd,null);assert.equal(data.runs[0].jobs[0].input.prompt,data.runs[0].jobs[1].input.prompt);
 let calls=JSON.parse(fs.readFileSync(path.join(tmp,'mock-calls.json')));assert.equal(calls.calls.filter(c=>c.method==='POST'&&!c.path.startsWith('/estimate/')).length,2);assert.ok(calls.maxUnfinished<=2);
 q=(await post('/api/estimate',{...payload,settings:{...settings,prompt:'over budget'}})).data;assert.equal(q.canStart,false);assert.equal((await post('/api/start',{quoteId:q.id})).status,400);
 q=(await post('/api/estimate',{...payload,settings:{...settings,prompt:'missing price'}})).data;assert.equal(q.totalUsd,null);assert.equal(q.canStart,false);
 q=(await post('/api/estimate',{...payload,mode:'single',modelIds:['wanprime'],settings:{...settings,prompt:'uncertain'}})).data;await post('/api/start',{quoteId:q.id});await new Promise(r=>setTimeout(r,100));data=await fetch(base+'/api/runs').then(r=>r.json());assert.equal(data.runs[0].jobs[0].status,'uncertain');assert.equal(data.runs[0].jobs[0].reservedUsd,.2);
 assert.equal((await post('/api/budget',{limitUsd:0.1})).status,400);
 child.kill();await once(child,'exit');child=start();await Promise.race([once(child.stdout,'data'),once(child.stderr,'data').then(([b])=>{throw new Error(b.toString())})]);boot=await bootstrap();data=await fetch(base+'/api/runs').then(r=>r.json());assert.equal(data.runs.length,2);assert.equal(data.runs[0].jobs[0].status,'uncertain');assert.equal(data.budget.reservedUsd,.2);
 assert.ok(!JSON.stringify(data).includes('test:test'));assert.ok(!JSON.stringify(boot).includes('test:test'));
 child.kill();await once(child,'exit');
 // Delete only the exact temporary directory created by mkdtemp above.
 fs.rmSync(tmp,{recursive:true,force:true});
});
